jobs:
  build:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - run: checkout
      - run: npm audit

workflow:
  default:
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
          requires:
            - test
